#index:
#    path: /
#    controller: App\Controller\DefaultController::index
main:
    path: /
    controller: App\Controller\DefaultController::index  
section:
    path: /section/{id}
    controller: App\Controller\SectionController::section     
section_red:
    path: /section_red/{id}
    controller: App\Controller\SectionController::edite   
section_save:
    path: /section_save
    controller: App\Controller\SectionController::save 